### PR TITLE
Base array-ness on `isArray`

### PR DESCRIPTION
**Pull request by bakkot**
Without this, 
```js
stringify({ __proto__: Array.prototype, length: 1, 0: 'a' });
```
gives
```js
'["a"]'
```

Contrast
```js
JSON.stringify({ __proto__: Array.prototype, length: 1, 0: 'a' })
```
which gives
```js
'{"0":"a","length":1}'
```

With this PR, trying to do this throws.

(JSON.stringify uses the same check as `isArray` internally.)

### CODE REVIEW

**Comment by qntm** [comment]
Good catch, using `Array.isArray(x)` instead of `Object.getPrototypeOf(x) === Array.prototype` seems like a strong move. But I think that inner test `if (proto !== Array.prototype) { ... }` can never return `true`, rendering the inner block unreachable. I don't think that second test is needed at all.

**Comment by bakkot** [comment]
Sure it can, two ways:

```js
stringify(Object.setPrototypeOf([], null))
stringify(new (class extends Array {}))
```

Added those as tests, for completeness.

**Comment by qntm** [comment]
Aha, I see... in that case is there something we can do about the case of e.g. `Object.setPrototypeOf(/* any non-object */, Object.prototype)`? In general, as a new bullet point in the README (which I haven't updated yet), I guess this is

* objects whose prototypes have been modified using `__proto__` or `Object.setPrototypeOf`

**Comment by bakkot** [comment]
> in that case is there something we can do about the case of 

There is no general purpose solution. There are one-offs for a lot of cases, which are generally based on builtin methods which as part of their implementation read some property which only special objects have, and otherwise throw. ljharb maintains a collection:
- [is-boxed-primitive](https://github.com/ljharb/is-boxed-primitive)
- [is-regex](https://github.com/ljharb/is-regex)
- [is-date-object](https://github.com/ljharb/is-date-object)
- [is-arguments](https://github.com/ljharb/is-arguments)
- [is-typed-array](https://github.com/ljharb/is-typed-array)

and you can also do things like
```js
const isMap = o => { try { Map.prototype.has.call(o, {}); return true; } catch { return false; } };
const isSet = o => { try { Set.prototype.has.call(o, {}); return true; } catch { return false; } };
const isWeakMap = o => { try { WeakMap.prototype.has.call(o, {}); return true; } catch { return false; } };
const isWeakSet = o => { try { WeakSet.prototype.has.call(o, {}); return true; } catch { return false; } };
```

On the other hand, I'd encourage thinking of most of these as being analogous to

```js
const isMyThing = new WeakSet;
function makeMyThing() {
  const o = {
    check() {
      return isMyThing.has(this);
    },
  };
  isMyThing.add(o);
  return o;
}
```

i.e., rather than the objects themselves being special, they're just used as keys in some side table where the data actually lives. In that case it seems permissible for `stringify` to ignore the side table. Arrays really are a special case, both because `JSON.stringify` knows about them and because their `length` attribute is genuinely magic.

**Pull request merged**
